---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.19"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]

# if you want to choose our nodes to deployed in specific nodes, we use nodegroups
# for ex. we want to deploy our DB to reside in High RAM instances, we define the group here 
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  # We use SSM session manager, to access cluster
  ssh:
    enableSsm: true
