apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-plaintext
  labels: 
    owner: Shahab
    app: webapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "pink"
    name: webapp-color-plaintext
    ports:
    - containerPort: 8080
      protocol: TCP

