apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-env
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    - name: COLOR_FROM_ENV
      value: "pink"
    name: webapp-color
  #   volumeMounts:
  #   - name: html
  #     mountPath: /var/htdocs
  # - image: nginx:alpine
  #   name: web-server
    # volumeMounts:
    # - name: html
    #   mountPath: /usr/share/nginx/html
    #   readOnly: true
    ports:
    - containerPort: 8080
      protocol: TCP
  # volumes:
  # - name: html
  #   emptyDir: {}

