apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-hp
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb
