apiVersion: v1
kind: Pod
metadata:
  name: webapp-color-env-from-configmap
  labels: 
    app: webapp
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    env:
    # It will accept APP_COLOR as environment variable (Line 39 app.py)
    - name: APP_COLOR
      valueFrom: 
        secretKeyRef:
          name: mysecret-webapp
          key: PASSWORD
    name: webapp-color-secret
    ports:
    - containerPort: 8080
      protocol: TCP

